markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-relative-links
  - algoliasearch-jekyll

versions:
  - v6
  - v5
  - v2

docroots: 
  v6: latest
  v5: v5
  v2: v2

version: v6
islatest: true

elasticsearch:
  currentversion: 6.1.1
  previousversion: 6.1.0

searchguard:
  currentversion: 6.x-20
  fullcurrentversion: 6.1.1-20.1
  
index: true

labels:
  navigation:
    quickstart: Quickstart
    installation: Installation
    tls: TLS Setup
    configuration: "Configuration"
    authauth: Authentication and Authorization
    rolespermissions: "Users, Roles and Permissions"
    eeadvanced: Advanced Security Features
    dlsfls: Document- and Field-Level Security
    auditlog: Audit Logging
    restapi: REST API
    esstack: Integrating with the Elastic stack
    xpack: Integrating with X-Pack
    integration_other: Other Integrations
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    v6: Search Guard 6
    v5: Search Guard 5
    v2: Search Guard 2
  collections:
    docs: Documentation
    troubleshooting: Troubleshooting
    changelogs: Changelogs


relative_links:
  enabled:     true
  collections: true

baseurl: /latest

collections:
  docs:
    output: true
    permalink: :title
  troubleshooting:
    output: true
    permalink: :title
  changelogs:
    output: true
    permalink: :title

algolia:
  application_id: '2ESDTH812Y'
  index_name:     'latest'
  record_css_selector: 'h1, h2, h3, h4, h5'
  allowed_extensions:
    - html
  settings:
    minWordSizefor1Typo: 4
    minWordSizefor2Typos: 8
    hitsPerPage: 20
    maxValuesPerFacet: 100
    version: 2
    attributesToIndex:
      - tags
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - text_all
    attributesToRetrieve: 
      - collection_name
      - text_all
      - unique_hierarchy
      - css_selector
      - url
      - tags
    ignorePlurals: true
    removeStopWords: true
    distinct: true
    attributesForFaceting:
      - category_name
      - h1
    attributesToSnippet: 
      - "text_all:150"
    attributesToHighlight:
      - text
      - text_all
    paginationLimitedTo: 1000
    attributeForDistinct: unique_hierarchy
    exactOnSingleWordQuery: attribute
    disableTypoToleranceOnAttributes:
      - h1
      - h2
      - h3
    ranking: 
      - typo
      - geo
      - words
      - filters
      - proximity
      - attribute
      - exact
      - custom
    customRanking:
      - desc(posted_at)
      - desc(weight.tag_name)
      - asc(weight.position)
    separatorsToIndex: "."
    removeWordsIfNoResults: lastWords
    queryType: prefixLast
    snippetEllipsisText: "..."
    alternativesAsExact: 
      - ignorePlurals
      - singleWordSynonym
